// Canonical files stay in the Cargo package. Worker copies are generated bytes.
import manifest from '../crates/svg-language-server/assets/baseline-icons.json' with { type: 'json' };

const canonical = new URL('../crates/svg-language-server/assets/', import.meta.url);
const copies = new URL('../workers/svg-compat/static/badges/', import.meta.url);
const mode = Deno.args[0] ?? '--check';
if (Deno.args.length > 1 || !['--check', '--sync', '--upstream'].includes(mode)) {
	throw new Error('Usage: baseline-icons.ts [--check|--sync|--upstream]');
}

const names = ['widely', 'newly', 'limited'].flatMap(status => ['', '-dark'].map(theme => `baseline-${status}-icon${theme}.svg`));
const hashes: Record<string, string> = manifest.sha256;
if (
	manifest.repository !== 'https://github.com/web-platform-dx/web-platform-dx.github.io'
	|| manifest.directory !== 'src/assets/img'
	|| !/^[a-f0-9]{40}$/.test(manifest.revision)
	|| Object.keys(hashes).length !== names.length
	|| names.some(name => !/^[a-f0-9]{64}$/.test(hashes[name] ?? ''))
) throw new Error('Invalid Baseline asset manifest');

async function sha256(bytes: Uint8Array): Promise<string> {
	const digest = await crypto.subtle.digest('SHA-256', new Uint8Array(bytes));
	return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, '0')).join('');
}

for (const directory of [canonical, copies]) {
	for await (const entry of Deno.readDir(directory)) {
		if (entry.name.startsWith('baseline-') && entry.name.endsWith('.svg') && !names.includes(entry.name)) {
			throw new Error(`Unexpected Baseline copy: ${new URL(entry.name, directory)}`);
		}
	}
}

// Validate every original before writing any generated copy.
const originals = await Promise.all(names.map(async name => {
	const bytes = await Deno.readFile(new URL(name, canonical));
	if (await sha256(bytes) !== hashes[name]) throw new Error(`Canonical icon changed: ${name}`);
	return { name, bytes };
}));

for (const { name, bytes } of originals) {
	const destination = new URL(name, copies);
	if (mode === '--sync') await Deno.writeFile(destination, bytes);
	if (await sha256(await Deno.readFile(destination)) !== hashes[name]) {
		throw new Error(`Worker copy differs: ${name}. Run just baseline-icons-sync.`);
	}
	if (mode === '--upstream') {
		const url = `https://raw.githubusercontent.com/web-platform-dx/web-platform-dx.github.io/${manifest.revision}/${manifest.directory}/${name}`;
		const response = await fetch(url);
		if (!response.ok) throw new Error(`Cannot verify ${name}: HTTP ${response.status}`);
		if (await sha256(new Uint8Array(await response.arrayBuffer())) !== hashes[name]) {
			throw new Error(`Pinned upstream bytes differ: ${name}`);
		}
	}
}
console.log(`Baseline icons: ${names.length} canonical assets and worker copies verified${mode === '--upstream' ? ' against pinned upstream' : ''}.`);
