//! Build script: generate the runtime catalog from the committed, extracted
//! structured spec data.
//!
//! The extraction pipeline (a separate `regen` step) fetches canonical upstream
//! and writes structured JSON under `data/`. This script reads that JSON and
//! emits `catalog.rs` (static `ElementDef`/`AttributeDef` arrays) into `OUT_DIR`,
//! which `src/catalog.rs` includes. When the data has not been generated yet,
//! it emits an empty catalog so the crate still compiles.

use std::{env, fs, path::PathBuf};

fn main() {
    let Some(out_dir) = env::var_os("OUT_DIR") else {
        panic!("OUT_DIR must be set by cargo");
    };
    let out_dir = PathBuf::from(out_dir);
    let data_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data");

    println!("cargo::rerun-if-changed=data");
    println!("cargo::rerun-if-changed=build.rs");

    // Until the extraction pipeline has populated `data/`, emit an empty
    // catalog so the crate (and the workspace) compiles.
    let catalog = if data_dir.is_dir() {
        generate_catalog(&data_dir)
    } else {
        empty_catalog()
    };

    let catalog_path = out_dir.join("catalog.rs");
    if let Err(error) = fs::write(&catalog_path, catalog) {
        panic!("write {}: {error}", catalog_path.display());
    }
}

/// Placeholder catalog used before any spec data has been extracted.
fn empty_catalog() -> String {
    [
        "// Generated by build.rs — empty (no extracted data yet).",
        "pub static ELEMENTS: &[crate::types::ElementDef] = &[];",
        "pub static ATTRIBUTES: &[crate::types::AttributeDef] = &[];",
        "pub static SNAPSHOT_METADATA: &[crate::types::SnapshotMetadata] = &[];",
    ]
    .join("\n")
}

/// Generate the catalog from extracted JSON. Populated as the extraction
/// pipeline lands; for now it falls back to the empty catalog.
fn generate_catalog(_data_dir: &std::path::Path) -> String {
    // TODO(extraction): read `data/specs/*/...json` and emit populated static
    // arrays. Until the extractors land, an empty catalog keeps the build green.
    empty_catalog()
}
