//! Build script: generate the runtime catalog from the committed, extracted
//! structured spec data.
//!
//! The extraction pipeline (a separate `regen` step) fetches canonical upstream
//! and writes structured JSON under `data/`. This script reads that JSON and
//! emits `catalog.rs` (static `ElementDef`/`AttributeDef` arrays) into `OUT_DIR`,
//! which `src/catalog.rs` includes. When the data has not been generated yet,
//! it emits an empty catalog so the crate still compiles.

use std::{env, fmt::Write as _, fs, path::Path, path::PathBuf};

use serde::Deserialize;

/// The committed catalog, mirroring `svg-data-regen`'s output shape.
#[derive(Deserialize)]
struct Catalog {
    elements: Vec<Element>,
}

/// One element entry from `catalog.json`.
#[derive(Deserialize)]
struct Element {
    name: String,
    spec_url: Option<String>,
    content_model: ContentModel,
    attrs: Vec<String>,
    global_attrs: bool,
}

/// The content-model shapes the catalog encodes (already flattened).
#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum ContentModel {
    ChildrenSet { elements: Vec<String> },
    AnySvg,
    Text,
}

fn main() {
    let Some(out_dir) = env::var_os("OUT_DIR") else {
        panic!("OUT_DIR must be set by cargo");
    };
    let out_dir = PathBuf::from(out_dir);
    let data_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data");

    println!("cargo::rerun-if-changed=data");
    println!("cargo::rerun-if-changed=build.rs");

    let catalog = generate_catalog(&data_dir);

    let catalog_path = out_dir.join("catalog.rs");
    if let Err(error) = fs::write(&catalog_path, catalog) {
        panic!("write {}: {error}", catalog_path.display());
    }
}

/// Generate the catalog source. Reads `data/catalog.json` when present, else
/// emits an empty catalog so the crate still compiles before a regeneration.
fn generate_catalog(data_dir: &Path) -> String {
    let catalog_path = data_dir.join("catalog.json");
    let Ok(json) = fs::read_to_string(&catalog_path) else {
        return empty_catalog();
    };
    let catalog: Catalog = match serde_json::from_str(&json) {
        Ok(catalog) => catalog,
        Err(error) => panic!("parse {}: {error}", catalog_path.display()),
    };
    emit_catalog(&catalog)
}

/// Placeholder catalog used before any spec data has been extracted.
fn empty_catalog() -> String {
    [
        "// Generated by build.rs - empty (no extracted data yet).",
        "pub static ELEMENTS: &[crate::types::ElementDef] = &[];",
        "pub static ATTRIBUTES: &[crate::types::AttributeDef] = &[];",
        "pub static SNAPSHOT_METADATA: &[crate::types::SnapshotMetadata] = &[];",
    ]
    .join("\n")
}

/// Emit the catalog as Rust source: a static `ElementDef` array, plus the
/// still-empty attribute and snapshot arrays (populated by later phases).
fn emit_catalog(catalog: &Catalog) -> String {
    let mut out = String::from("// Generated by build.rs from data/catalog.json.\n");
    out.push_str("pub static ELEMENTS: &[crate::types::ElementDef] = &[\n");
    for element in &catalog.elements {
        emit_element(&mut out, element);
    }
    out.push_str("];\n");
    out.push_str("pub static ATTRIBUTES: &[crate::types::AttributeDef] = &[];\n");
    out.push_str("pub static SNAPSHOT_METADATA: &[crate::types::SnapshotMetadata] = &[];\n");
    out
}

/// Append one `ElementDef` literal. Spec-derived fields are filled; the
/// browser-compat fields (`mdn_url`, `baseline`, `browser_support`, `verdicts`)
/// and the spec `description` default empty until their phases land.
fn emit_element(out: &mut String, element: &Element) {
    let spec_url = element
        .spec_url
        .as_ref()
        .map_or_else(|| "None".to_owned(), |url| format!("Some({url:?})"));
    let content_model = match &element.content_model {
        ContentModel::ChildrenSet { elements } => {
            format!(
                "crate::types::ContentModel::ChildrenSet(&[{}])",
                quote_list(elements)
            )
        }
        ContentModel::AnySvg => "crate::types::ContentModel::AnySvg".to_owned(),
        ContentModel::Text => "crate::types::ContentModel::Text".to_owned(),
    };
    let _ = writeln!(
        out,
        "    crate::types::ElementDef {{ name: {:?}, description: \"\", mdn_url: \"\", \
         spec_url: {spec_url}, deprecated: false, experimental: false, baseline: None, \
         browser_support: None, verdicts: &[], content_model: {content_model}, \
         attrs: &[{}], global_attrs: {} }},",
        element.name,
        quote_list(&element.attrs),
        element.global_attrs,
    );
}

/// Render a slice of strings as comma-separated Rust string literals.
fn quote_list(items: &[String]) -> String {
    items
        .iter()
        .map(|item| format!("{item:?}"))
        .collect::<Vec<_>>()
        .join(", ")
}
