//! Build script: generate the runtime catalog from the committed, extracted
//! structured spec data.
//!
//! The extraction pipeline (a separate `regen` step) fetches canonical upstream
//! and writes structured JSON under `data/`. This script reads that JSON and
//! emits `catalog.rs` (static `ElementDef`/`AttributeDef` arrays) into `OUT_DIR`,
//! which `src/catalog.rs` includes. When the data has not been generated yet,
//! it emits an empty catalog so the crate still compiles.

use std::{env, fmt::Write as _, fs, path::Path, path::PathBuf};

use serde::Deserialize;

const CATALOG_SCHEMA_VERSION: u16 = 1;

/// The committed catalog, mirroring `svg-data-regen`'s output shape.
#[derive(Deserialize)]
struct Catalog {
    schema_version: u16,
    elements: Vec<Element>,
    #[serde(default)]
    attributes: Vec<Attribute>,
}

/// One element entry from `catalog.json`.
#[derive(Deserialize)]
struct Element {
    name: String,
    spec_url: Option<String>,
    content_model: ContentModel,
    attrs: Vec<String>,
    global_attrs: bool,
}

/// The content-model shapes the catalog encodes (already flattened).
#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum ContentModel {
    ChildrenSet { elements: Vec<String> },
    AnySvg,
    Foreign,
    Text,
}

/// One attribute entry from `catalog.json`.
#[derive(Deserialize)]
struct Attribute {
    name: String,
    spec_url: Option<String>,
    animatable: bool,
    #[serde(rename = "presentation_attribute")]
    presentation: Option<String>,
    values: AttributeValues,
    applicability: AttributeApplicability,
}

/// The attribute value-space shapes the catalog encodes.
#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum AttributeValues {
    Enum { values: Vec<String> },
    Transform { functions: Vec<String> },
    Color,
    Length,
    Url,
    NumberOrPercentage,
    FreeText,
}

/// Which elements the catalog says an attribute can appear on.
#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum AttributeApplicability {
    Global,
    Elements { elements: Vec<String> },
    None,
}

fn main() {
    let Some(out_dir) = env::var_os("OUT_DIR") else {
        panic!("OUT_DIR must be set by cargo");
    };
    let out_dir = PathBuf::from(out_dir);
    let data_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data");

    println!("cargo::rerun-if-changed=data");
    println!("cargo::rerun-if-changed=build.rs");

    let catalog = generate_catalog(&data_dir);

    let catalog_path = out_dir.join("catalog.rs");
    if let Err(error) = fs::write(&catalog_path, catalog) {
        panic!("write {}: {error}", catalog_path.display());
    }
}

/// Generate the catalog source. Reads `data/catalog.json` when present, else
/// emits an empty catalog so the crate still compiles before a regeneration.
fn generate_catalog(data_dir: &Path) -> String {
    let catalog_path = data_dir.join("catalog.json");
    let Ok(json) = fs::read_to_string(&catalog_path) else {
        return empty_catalog();
    };
    let catalog: Catalog = match serde_json::from_str(&json) {
        Ok(catalog) => catalog,
        Err(error) => panic!("parse {}: {error}", catalog_path.display()),
    };
    assert_eq!(
        catalog.schema_version,
        CATALOG_SCHEMA_VERSION,
        "{} has schema_version {}, expected {}",
        catalog_path.display(),
        catalog.schema_version,
        CATALOG_SCHEMA_VERSION
    );
    emit_catalog(&catalog)
}

/// Placeholder catalog used before any spec data has been extracted.
fn empty_catalog() -> String {
    [
        "// Generated by build.rs - empty (no extracted data yet).",
        "pub static ELEMENTS: &[crate::types::ElementDef] = &[];",
        "pub static ATTRIBUTES: &[crate::types::AttributeDef] = &[];",
        "pub static SNAPSHOT_METADATA: &[crate::types::SnapshotMetadata] = &[];",
    ]
    .join("\n")
}

/// Emit the catalog as Rust source: static `ElementDef` and `AttributeDef`
/// arrays, plus the still-empty snapshot array (populated by later phases).
fn emit_catalog(catalog: &Catalog) -> String {
    let mut out = String::from("// Generated by build.rs from data/catalog.json.\n");
    out.push_str("pub static ELEMENTS: &[crate::types::ElementDef] = &[\n");
    for element in &catalog.elements {
        emit_element(&mut out, element);
    }
    out.push_str("];\n");
    out.push_str("pub static ATTRIBUTES: &[crate::types::AttributeDef] = &[\n");
    for attribute in &catalog.attributes {
        emit_attribute(&mut out, attribute);
    }
    out.push_str("];\n");
    out.push_str("pub static SNAPSHOT_METADATA: &[crate::types::SnapshotMetadata] = &[];\n");
    out
}

/// Append one `ElementDef` literal. Spec-derived fields are filled; the
/// browser-compat fields (`mdn_url`, `baseline`, `browser_support`, `verdicts`)
/// and the spec `description` default empty until their phases land.
fn emit_element(out: &mut String, element: &Element) {
    let spec_url = element
        .spec_url
        .as_ref()
        .map_or_else(|| "None".to_owned(), |url| format!("Some({url:?})"));
    let content_model = match &element.content_model {
        ContentModel::ChildrenSet { elements } => {
            format!(
                "crate::types::ContentModel::ChildrenSet(&[{}])",
                quote_list(elements)
            )
        }
        ContentModel::AnySvg => "crate::types::ContentModel::AnySvg".to_owned(),
        ContentModel::Foreign => "crate::types::ContentModel::Foreign".to_owned(),
        ContentModel::Text => "crate::types::ContentModel::Text".to_owned(),
    };
    let _ = writeln!(
        out,
        "    crate::types::ElementDef {{ name: {:?}, description: \"\", mdn_url: \"\", \
         spec_url: {spec_url}, deprecated: false, experimental: false, baseline: None, \
         browser_support: None, verdicts: &[], content_model: {content_model}, \
         attrs: &[{}], global_attrs: {} }},",
        element.name,
        quote_list(&element.attrs),
        element.global_attrs,
    );
}

/// Append one `AttributeDef` literal. Spec-derived fields are filled; browser
/// compat and prose fields default empty until later phases land.
fn emit_attribute(out: &mut String, attribute: &Attribute) {
    let spec_url = attribute
        .spec_url
        .as_ref()
        .map_or_else(|| "None".to_owned(), |url| format!("Some({url:?})"));
    let presentation_attribute = attribute
        .presentation
        .as_ref()
        .map_or_else(|| "None".to_owned(), |name| format!("Some({name:?})"));
    let values = emit_attribute_values(&attribute.values);
    let applicability = emit_attribute_applicability(&attribute.applicability);
    let _ = writeln!(
        out,
        "    crate::types::AttributeDef {{ name: {:?}, description: \"\", mdn_url: \"\", \
         spec_url: {spec_url}, deprecated: false, experimental: false, animatable: {}, \
         presentation_attribute: {presentation_attribute}, baseline: None, browser_support: None, \
         verdicts: &[], values: {values}, value_overrides: &[], applicability: {applicability} }},",
        attribute.name, attribute.animatable,
    );
}

/// Render an attribute value-space literal.
fn emit_attribute_values(values: &AttributeValues) -> String {
    match values {
        AttributeValues::Enum { values } => {
            format!(
                "crate::types::AttributeValues::Enum(&[{}])",
                quote_list(values)
            )
        }
        AttributeValues::Transform { functions } => {
            format!(
                "crate::types::AttributeValues::Transform(&[{}])",
                quote_list(functions)
            )
        }
        AttributeValues::Color => "crate::types::AttributeValues::Color".to_owned(),
        AttributeValues::Length => "crate::types::AttributeValues::Length".to_owned(),
        AttributeValues::Url => "crate::types::AttributeValues::Url".to_owned(),
        AttributeValues::NumberOrPercentage => {
            "crate::types::AttributeValues::NumberOrPercentage".to_owned()
        }
        AttributeValues::FreeText => "crate::types::AttributeValues::FreeText".to_owned(),
    }
}

/// Render an attribute applicability literal.
fn emit_attribute_applicability(applicability: &AttributeApplicability) -> String {
    match applicability {
        AttributeApplicability::Global => "crate::types::AttributeApplicability::Global".to_owned(),
        AttributeApplicability::Elements { elements } => {
            format!(
                "crate::types::AttributeApplicability::Elements(&[{}])",
                quote_list(elements)
            )
        }
        AttributeApplicability::None => "crate::types::AttributeApplicability::None".to_owned(),
    }
}

/// Render a slice of strings as comma-separated Rust string literals.
fn quote_list(items: &[String]) -> String {
    items
        .iter()
        .map(|item| format!("{item:?}"))
        .collect::<Vec<_>>()
        .join(", ")
}
